application: mm-proxy
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: trf.maps.yandex

- url: /test
  script: test

- url: /yaroute
  script: yaroute

- url: /trf.maps.yandex
  script: trf.maps.yandex
